### ISSUE TITLE
question regarding context.Context

### ISSUE THREAD

**Issue by ultperf** [cloudwego/hertz#435]
just curious why need context.Context because fasthttp doesnt have this. cant just incorporate into ctx?
what is the purpose of cc context.Context?
```
func hertzProxy(cc context.Context, ctx *app.RequestContext) {

}
```

**Comment by ultperf** [comment]
what is the use of context.Context then? in what circumstances will it be used?

**Comment by li-jin-gou** [comment]
This is a good question.

The call link information will be stored using context.Context, such as logid、spanid、env_name etc. There is a high probability that this information will be used asynchronously.

The request context is more focused on handling requests and responses.

**Comment by li-jin-gou** [comment]
refer to https://www.cloudwego.io/docs/hertz/faq/#context-guide

**Comment by ultperf** [comment]
pls provide examples of when or how to work with c context.Content
thx

**Comment by Duslia** [comment]
You can use it for trace and metrics.
https://github.com/hertz-contrib/obs-opentelemetry
https://github.com/hertz-contrib/monitor-prometheus

**Comment by Duslia** [comment]
The processing function (HandlerFunc) of the Hertz route does not receive the standard context.Context. We have found in a lot of practice that the business side usually needs a standard context to be passed between RPC Client or logs, Tracing and other components, but due to the request The life cycle of the context (RequestContext) is limited to one HTTP request, and the above-mentioned scenarios often have asynchronous delivery and processing, resulting in some data inconsistencies if the request context is directly delivered. We have made many attempts to this end, but because the core reason is that the life cycle of the request context (RequestContext) cannot be extended gracefully on demand, and finally under various design trade-offs, we add a standard context entry to the routing handler function signature Parameters, by separating two contexts with different life cycles, fundamentally solve various abnormal problems caused by inconsistent life cycles of contexts.

**Comment by Duslia** [comment]
RequestContext contains all information about once request, like request, response, header and so on. It is constructed by framework and you don't need to feel it. Standard context is a empty context if you don't put data on it.

**Comment by Duslia** [comment]
> You can use it for trace and metrics. https://github.com/hertz-contrib/obs-opentelemetry https://github.com/hertz-contrib/monitor-prometheus

here

**Comment by li-jin-gou** [comment]
thanks provide a good example.
