### ISSUE TITLE
Initialization project by hz reports a warning

### ISSUE THREAD

**Issue by beanbest** [cloudwego/hertz#648]
**Describe the bug**

Initialization project by hz reports a warning：
```
mkdir hertz_demo
cd hertz_demo
hz new
```
```
do not generate 'go.mod', please add 'replace github.com/apache/thrift => github.com/apache/thrift v0.13.0' to your 'go.mod'
```

**Hertz version:**
```
hz version v0.6.1
```
**Go version:**

```
linux go1.20.1
```

**Comment by FGYFFFF** [comment]
@beanbest ~~~ This is a hint, because you did not specify "--mod", so the tool does not generate the "go.omd" file for you, preventing the "go.mod" from being overwritten in the previous project. You can initialize your "go.mod" with "go mod init". This is a new feature, we consider to optimize the tips .Are you willing to contribute to this optimization?
